# Generated by Django 5.2.3 on 2026-07-31 22:40

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClicAnnonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annonce_id', models.IntegerField()),
                ('date_clic', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('date_de_naissance', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_annonce', models.CharField(choices=[('vente', 'Mise en vente'), ('location', 'Mise en location')], db_index=True, max_length=20)),
                ('standing', models.CharField(choices=[('entree_couchee', 'Entrée couchée'), ('1ch_salon', '1 chambre un salon'), ('1ch_salon_douche', '1 chambre un salon couloir douche'), ('2ch_salon', '2 chambres salon'), ('3ch_salon', '3 chambres salon'), ('villa_meuble', 'Villa meublé'), ('villa_non_meuble', 'Villa non meublé'), ('app_meuble', 'Appartement meublé'), ('app_non_meuble', 'Appartement non meublé'), ('quest_house', 'Quest house'), ('parcelle_location', 'Parcelle (LOCATION)'), ('villa', 'Villa'), ('maison', 'Maison'), ('parcelle_vente', 'Parcelle (VENTE)')], db_index=True, max_length=17)),
                ('prix', models.DecimalField(db_index=True, decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('description', models.TextField(blank=True, null=True)),
                ('quartier', models.CharField(db_index=True, max_length=100)),
                ('coordonnes_google_maps', models.URLField(blank=True, null=True)),
                ('numero_telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=20, region='BJ')),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('est_publiee', models.BooleanField(db_index=True, default=False)),
                ('est_disponible', models.BooleanField(db_index=True, default=True)),
                ('nbr_vues', models.IntegerField(db_index=True, default=0)),
                ('nbr_clics', models.IntegerField(db_index=True, default=0)),
                ('utilisateurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=500, upload_to='annonces/%Y/%m/%d/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('est_disponible', models.BooleanField(default=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='annonces.annonce')),
            ],
        ),
        migrations.AddIndex(
            model_name='annonce',
            index=models.Index(fields=['est_publiee', 'type_annonce'], name='annonces_an_est_pub_72d5a2_idx'),
        ),
        migrations.AddIndex(
            model_name='annonce',
            index=models.Index(fields=['quartier'], name='annonces_an_quartie_0c6f81_idx'),
        ),
        migrations.AddIndex(
            model_name='annonce',
            index=models.Index(fields=['prix'], name='annonces_an_prix_81ede3_idx'),
        ),
        migrations.AddIndex(
            model_name='annonce',
            index=models.Index(fields=['est_disponible'], name='annonces_an_est_dis_43cd1d_idx'),
        ),
    ]
