# Generated by Django 6.0.7 on 2026-08-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0002_demandevisite_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type_utilisateur',
            field=models.CharField(choices=[('locataire', 'Locataire'), ('proprietaire', 'Propriétaire')], default='locataire', max_length=20),
        ),
    ]
